### ISSUE TITLE
Hadashboard Error Getting State

### ISSUE THREAD

**Issue by DankRadon** [vkorn/hassio-addons#9]
When I reload my dashboard I get a dialog box saying "Error getting state, check Java console for details".

It's entirely possible I have my configuration completely messed up...

**appdaemon.yaml**

```
AppDaemon:
  cert_verify: False
  disable_apps: 1
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  app_dir: /config/hadaemon/apps
HASS:
  ha_url: http://192.168.1.254:8123
HADashboard:
  dash_url: http://cp.local.io
  dash_dir: /config/hadaemon/dashboards
```

**Add-on Options**
```
{
  "domain": "cp.local.io"
}
```

**Network Host**
3030

**Dashboard**

```
#
# Main arguments, all optional
#
title: Main Panel
widget_dimensions: [122, 120]
widget_margins: [5, 5]
columns: 2
#
# Layout
#    
layout:
    - Back, Lamp

Back:
  widget_type: light
  title: Back
  title2: Light
  entity: light.back

Lamp:
   widget_type: light
   entity: light.living_room_lamp
   title: Lamp
```
